{% set version = "0.3.3" %}

package:
  name: vale-styles-proselint
  version: {{ version }}

source:
  - folder: proselint
    fn: vale-proselint-0.3.3.zip
    url: https://github.com/errata-ai/proselint/releases/download/v{{ version }}/proselint.zip
    sha256: d2c411bd383ac547762fd1f130506e597415c373364ad60b827478786681ba7a
  - fn: LICENSE-vale-proselint-0.3.3
    url: https://raw.githubusercontent.com/errata-ai/proselint/v{{ version }}/LICENSE
    sha256: b1f23c552b813bb86d87ed697d895a5e03bf80a3882f9ffd87fcdeb176f103c0

build:
  noarch: generic
  number: 0

requirements:
  host:
    - vale
  run:
    - vale

test:
  requires:
    - pytest

about:
  home: https://github.com/errata-ai/proselint
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: proselint rules for vale grammar and style checker

extra:
  recipe-maintainers:
    - bollwyvl
